The Levenshtein (minimum edit) distance between two strings is the minimum number of single-character edits (i.e., insertions, deletions, and substitutions) needed to transform one string into the other. The Levenshtein distance algorithm is useful for solving problems in natural language processing such as approximate string matching or fuzzy string searching.

In [167]:
# Import modules
import numpy as np
import pandas as pd
import Levenshtein as lev
from pprint import pprint

In [168]:
# Read CSV file into DataFrame
df = pd.read_csv("20210103_hundenamen.csv")
df.head(10)

HUNDENAME  GEBURTSJAHR_HUND GESCHLECHT_HUND
0                           Ituma              2011               w
1        "Bo" Bendy of Treegarden              2020               m
2           "Bobby" Lord Sinclair              2009               m
3      "Buddy" Fortheringhay's J.              2011               m
4    "Fly" Showring i fly for you              2015               w
5            "Pino" Ami du soleil              2010               m
6  "Zappalla II" Kora v. Tüfibach              2011               w
7  A great Dream Kajsa of Moss-La              2019               w
8                         A-Diana              2006               w
9              AISHA von der Mark              2020               w

In [169]:
dognames = df["HUNDENAME"].to_numpy()

In [170]:
# Compute the Levenshtein distance between each dog name
# and the name "Luca" using the Python Levenshtein package
levZs = np.array([lev.distance(dogname, "Luca") for dogname in dognames])

In [171]:
# Find all dog names with a Levenshtein distance of 1
dognames_oflevdist1 = np.unique(dognames[levZs == 1])
print("The Levenshtein distance between any two strings in [Luca, {}] is 1".format(", ".join(dognames_oflevdist1)))

The Levenshtein distance between any two strings in [Luca, Cuca, Lua, Luba, Lucas, Luce, Lucia, Lucy, Lula, Luma, Luna, Lupa, Yuca] is 1


In [172]:
# Implement the Levenshtein distance algorithm
def LevZ_algorithm(A, B, print_Emat=False):
    # Create a matrix E(i, j) to hold the edit distances
    # between the first i characters of the first string A
    # and the first j characters of the second string B
    E = np.zeros((len(A)+1, len(B)+1))
    nrows = E.shape[0]
    ncols = E.shape[1]
    
    # For each position i in the string A, and each position j in the string B,
    # compute the edit distance between the two substrings as E(i, j)
    E[0,:] = np.arange(ncols)
    E[:,0] = np.arange(nrows)
    for i in range(1, nrows):
        for j in range(1, ncols):
            E[i,j] = min(E[i-1,j] + 1, # cost of deletion
                         E[i,j-1] + 1, # cost of insertion
                         E[i-1,j-1] + int(A[i-1] != B[j-1])) # cost of substitution
    
    if print_Emat:
        print(E)
    
    return E[i,j];

In [173]:
# Compute the Levenshtein distance between each dog name
# and the name "Luca" using our homemade algorithm
levZs_check = np.array([LevZ_algorithm(dogname, "Luca") for dogname in dognames])
print("Our homemade Levenshtein distance algorithm gets {} edit distances wrong".format(sum(levZs != levZs_check)))

Our homemade Levenshtein distance algorithm gets 0 edit distances wrong


In [174]:
# Visualize the edit distance matrix for two strings, "Luca" and "Lucy"
_ = LevZ_algorithm("Luca", "Lucy", print_Emat=True)

[[0. 1. 2. 3. 4.]
 [1. 0. 1. 2. 3.]
 [2. 1. 0. 1. 2.]
 [3. 2. 1. 0. 1.]
 [4. 3. 2. 1. 1.]]
